### ISSUE TITLE
Add validation ability

### ISSUE THREAD

**Issue by matthew-inamdar** [goldspecdigital/oooas#11]
Add the ability to validate the built spec to see if it conforms.

It probably makes sense for the parent object to validate its children objects, as the validation differs depending on context. This is with exception of the base `OpenApi` object.

### Todo

- [x] Have `validate()` method on `OpenApi` class.
- [x] Either return `true` or a custom exception with a property containing an array of all the errors.
- [x] Update docs with usage.

**Comment by matthew-inamdar** [comment]
This has been implemented in #41 

I'd like to thank @vyuldashev for adding this feature as well all the other work he's done on this package!

I'm happy to share that he's now a maintainer for this package which will help get new features/bugfixes released quicker!
