### ISSUE TITLE
Allow specification extensions (^x-)

### ISSUE THREAD

**Issue by matthew-inamdar** [goldspecdigital/oooas#15]
### Links and resources
* https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#specification-extensions
> While the OpenAPI Specification tries to accommodate most use cases, additional data can be added to extend the specification at certain points.
> 
> The extensions properties are implemented as patterned fields that are always prefixed by `x-`.

### Todo
- [x] Base object to implement the feature.
- [x] `$object->x(string $key, mixed $value = 'X_EMPTY_VALUE'): self` setter method.
- [x] Empty value string indicates the value should be unset, this allows users to specify a null value.
- [x] `$object->xKey` getter in magic `__get()` method.
- [x] `toArray()` method to include all extensions provided.
- [x] `$object->xExtensions` getter to get the entire array.
